spring:
  application:
    name: svc-products
  config:
    import: optional:configserver:${SERVER_CONFIG:http://localhost:7070/}

management:
  endpoints:
    web:
      exposure:
        include: '*'